import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Headphones, Pause, Play, RotateCcw } from 'lucide-react';
import { getLearningPackage, updatePlayback } from '../services/learningPackageApi';
import { UserProfile } from '../types';

export default function LearningPackage({ id, currentUser, onBack }: { id: string; currentUser: UserProfile; onBack: () => void }) {
  const [data, setData] = useState<any>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [playing, setPlaying] = useState(false); const audio = useRef<HTMLAudioElement>();
  const load = async () => { setLoading(true); setError(''); try { setData(await getLearningPackage(id, currentUser.id)); } catch (e: any) { setError(e.message || '读取学习包失败'); } finally { setLoading(false); } };
  useEffect(() => { load(); return () => audio.current?.pause(); }, [id, currentUser.id]);
  const content = data?.content; const playback = data?.playback; const listening = content?.listening;
  const play = async () => { try { if (!playback?.canPlay) return; if (!audio.current) { const res = await fetch('/api/tts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(content.audio.request) }); const tts = await res.json(); if (!tts.success) throw new Error(tts.error || '音频生成失败'); const bytes = Uint8Array.from(atob(tts.audio), c => c.charCodeAt(0)); const element = new Audio(URL.createObjectURL(new Blob([bytes], { type: 'audio/mpeg' }))); element.onended = async () => { setPlaying(false); await updatePlayback(id, currentUser.id, 'completed'); await load(); }; audio.current = element; } await audio.current.play(); setPlaying(true); } catch (e: any) { setError(e.message || '播放失败'); } };
  if (loading) return <div className="p-6 text-slate-600" role="status">正在准备学习内容...</div>;
  if (error) return <section className="p-6"><button onClick={onBack} className="min-h-11 text-sm underline">返回智慧课堂</button><p className="mt-4 text-red-700" role="alert">{error}</p><button onClick={load} className="mt-4 min-h-11 border px-4">重试</button></section>;
  if (['english-video', 'math-video', 'chinese-video', 'science-video'].includes(data.kind)) return <section className="mx-auto max-w-4xl"><button onClick={onBack} className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm"><ArrowLeft size={18}/>返回智慧课堂</button><div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">视频学习已取消，历史学习包仅保留记录，不再提供资源查找或播放。</div></section>;
  if (data.kind === 'english-listening') return <section className="mx-auto max-w-4xl text-slate-800"><button onClick={onBack} className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm"><ArrowLeft size={18}/>返回智慧课堂</button><div className="border border-cyan-200 bg-white p-5"><p className="text-sm text-cyan-800">AI 原创听力练习</p><h1 className="mt-1 text-2xl font-semibold">英语听力</h1><p className="mt-2 text-sm text-slate-600">还可完整播放 {playback.playsRemaining} 次</p><div className="mt-5 flex gap-3"><button aria-label={playing ? '暂停播放' : '播放听力'} disabled={!playback.canPlay} onClick={() => playing ? (audio.current?.pause(), setPlaying(false)) : play()} className="grid h-11 w-11 place-items-center bg-cyan-700 text-white disabled:opacity-40">{playing ? <Pause size={20}/> : <Play size={20}/>}</button><button aria-label="重新开始" disabled={!playback.canPlay} onClick={() => { if (audio.current) { audio.current.currentTime = 0; play(); } }} className="grid h-11 w-11 place-items-center border disabled:opacity-40"><RotateCcw size={18}/></button></div></div>{playback.completedPlays > 0 && <div className="mt-6 space-y-4 border-t pt-5">{listening.questions.map((q: any) => <div key={q.id}><p className="font-medium">{q.prompt}</p>{q.options?.map((o: string) => <label key={o} className="mt-2 flex gap-2"><input type="radio" name={q.id}/>{o}</label>)}</div>)}<button onClick={async () => { await updatePlayback(id, currentUser.id, 'submit'); await load(); }} className="min-h-11 bg-slate-800 px-4 text-white">提交答案</button>{playback.submittedAt && <details><summary>查看文本与答案</summary><p className="mt-3 whitespace-pre-wrap">{listening.script}</p>{listening.questions.map((q: any) => <p key={q.id} className="mt-2 text-sm">{q.answer}：{q.rubricPoints.join('；')}</p>)}</details>}</div>}</section>;
  return <section className="mx-auto max-w-4xl"><button onClick={onBack} className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm"><ArrowLeft size={18}/>返回智慧课堂</button><h1 className="text-2xl font-semibold">数学思维训练</h1><p className="mt-4 rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-600">该学习内容请在智慧课堂任务详情中继续完成。</p></section>;
}
